#!/bin/bash

#1 scriptname > filename 重定向脚本的内容到文件中，覆盖文件原有内容



#2 command &> filename 重定向stdout和stderr到文件中



#3  command >&2 filename 重定向command 的stdout到stderr



#4 scriptname >> filename 重定向脚本的输出到文件中，添加到文件未断，如果没有文件，则创建这个文件



#5 远程替换
# (command)>
# <(command)



#6 <和>可用来做字符串比较



#7 <和>可用在数学计算比较



#8 << 重定向，用在"here document"



#9 <<< 重定向，用在"here string"



#10 <,> ASCII比较
veg1=carrots
veg2=tomatoes

if [[ "$veg1" < "$veg2" ]]
then
	echo "Although $veg1 precede $veg2 in the dictionary,"
	echo "this implies nothing about my culinary preferences."
else
	echo "What kind of dictionary are you using,anyhow?"
fi



#10 \<,\> 正则表达式中的单词边界，如
grep '\<the\>' /Users/h/test/dir.txt
