#!/bin/bash

#1 [] test
# test的表达式将在[]中
# 值得注意的是[是shell内建test命令的一部分，
# 并不是/usr/bin/test中的扩展命令的一个连接



#2 [[]] test
# test表达式放在[[]]中(shell关键字)



#3 数组元素
Array[1]=slot_1
echo ${Array[1]}



#4 字符范围，在正则表达式中使用，作为字符匹配的一个范围


